Select * from customer
limit 5;


--1. What is the total revenue generated by male vs female customers?

select "Gender", sum("Purchase Amount (USD)") from customer
group by "Gender";



--2. Which customers used a discount but still spent more than the average purchase amount?

Select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied" ='Yes' and "Purchase Amount (USD)" >= (select avg("Purchase Amount (USD)") from customer)


--3. What are the top 5 products with the highest average review rating?

Select "Item Purchased",  avg("Review Rating") as rating from customer
group by "Item Purchased"
order by rating desc
Limit 5;

--4. Compare the average Purchase Amounts between Standard and Express shipping
Select avg("Purchase Amount (USD)"), "Shipping Type"
from customer 
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"


--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subcribers?
Select avg("Purchase Amount (USD)") as avg ,sum("Purchase Amount (USD)") as sum, count("Customer ID"), "Subscription Status"
from customer
group by "Subscription Status";


--6. Which 5 product have the highest percentage of purchases with discounts applied?

Select "Item Purchased", sum(100* case when "Discount Applied"='Yes' then 1 else 0 end)/count(*) as discount_rate
from customer
group by "Item Purchased"
order by discount_rate desc
limit 5;


--7. Segment customers into new, returning and loyal based on their total number of previos purchases and show the count of each segment
with customer_type as(
select "Customer ID", "Previous Purchases",
case
    when "Previous Purchases"=1 then 'new'
	when "Previous Purchases" between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "no of customers"
from customer_type
group by customer_segment


--8. What are the top 3 most purchased products within each category?
with item_counts as(
select "Category",("Item Purchased"), count("Customer ID") as total_orders,
row_number() over (partition by "Category" order by count("Customer ID")desc) as item_rank
from customer
group by "Category", "Item Purchased"
)

select item_rank, "Category", "Item Purchased" , total_orders
from item_counts
where item_rank<=3;


--9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select "Subscription Status",
count("Customer ID") as repeat_buyers
from customer
where "Previous Purchases">5
group by "Subscription Status";

--10. What is the revenue contribution of each Item purchased?
select "Item Purchased",
sum("Purchase Amount (USD)") as Revenue
from customer
group by "Item Purchased"
order by Revenue desc;